services:
  # Node-RED service - สำหรับการพัฒนา flows และ dashboard
  nodered:
    image: nodered/node-red:latest
    container_name: workshop-nodered
    restart: unless-stopped
    user: "1000:1000"
    ports:
      - 0.0.0.0:1880:1880
    volumes:
      - ./node-red-data/data:/data
    environment:
      - TZ=${TZ:-Asia/Bangkok}
    networks:
      - iot-network

  # Mosquitto MQTT Broker - MQTT Broker เบาและมีประสิทธิภาพ
  # mosquitto:
  #   image: eclipse-mosquitto:latest
  #   container_name: workshop-mosquitto
  #   restart: unless-stopped
  #   ports:
  #     - "1883:1883"    # MQTT Protocol
  #     - "9001:9001"    # Websocket
  #   volumes:
  #     - ./mosquitto-config:/mosquitto/config
  #     - ./mosquitto-data/:/mosquitto/data
  #     - ./mosquitto-data:/mosquitto/log
  #   networks:
  #     - iot-network

  # EMQX - Enterprise MQTT Broker
  emqx:
    image: emqx/emqx:latest
    container_name: workshop-emqx
    restart: unless-stopped
    ports:
      - 0.0.0.0:1883:1883      # MQTT Port (แยกพอร์ตกับ Mosquitto)
      - 0.0.0.0:8083:8083      # MQTT/WebSocket
      - 0.0.0.0:8084:8084      # MQTT/WSS
      - 0.0.0.0:8883:8883      # MQTT/SSL
      - 0.0.0.0:18083:18083    # EMQX Dashboard
      - 0.0.0.0:8080:8080      # HTTP API
    volumes:
      - ./emqx-data:/opt/emqx/data
      - ./emqx-data/log:/opt/emqx/log
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:18083"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - EMQX_NAME=emqx
      - EMQX_DASHBOARD__DEFAULT_PASSWORD=${EMQX_DEFAULT_PASSWORD:-public}
      - EMQX_HOST=racksync.local
    networks:
      - iot-network

networks:
  iot-network:
    driver: bridge